#!/usr/bin/env bash
# Bash script that prints subdomain values

g_com ()
{
    grep -A1 'ANSWER SECTION:' | tail -n 1
}

if [ -z "$2" ]
then
    dig www."$1" | g_com | awk '{print "The subdomain www is a "$4" record and points to "$5}'
    dig lb-01."$1" | g_com | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5}'
    dig web-01."$1" | g_com | awk '{print "The subdomain web-01 is a "$4" record and points to "$5}'
    dig web-02."$1" | g_com | awk '{print "The subdomain web-02 is a "$4" record and points to "$5}'
else
    dig "$2"."$1" | g_com | awk '{print "The subdomain '"$2"' is a "$4" record and points to "$5}'
fi
