#!/usr/bin/env bash
# Bash script that install nginx web server and overwrite index.html

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
