#!/usr/bin/env bash
# Bash script configure your Nginx server so that /redirect_me is redirecting to another page.

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
config_def="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i "s|server_name\ _;|$config_def|" /etc/nginx/sites-available/default
sudo service nginx restart
