#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

if ! sudo grep -e "rewrite ^/redirect_me" /etc/nginx/sites-available/default
then
        link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
        config_def="listen 80 default_server;\n\trewrite ^/redirect_me/$ $link permanent;"
        sed -i "s|listen 80 default_server;|$config_def|" /etc/nginx/sites-available/default
fi

if ! sudo grep -e "error_page 404 /404.html;" /etc/nginx/sites-available/default
then
        err_info="location = /error-page.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
        err_dir="error_page 404 /404.html;\n\t$err_info"
        config_err="}\n\n\t$err_dir\n"
        sed -i "0,/}/ s|}|$config_err|" /etc/nginx/sites-available/default
fi

sudo service nginx restart

if ! sudo grep -e "add_header X-Served-By" /etc/nginx/nginx.conf
then
        host_n="$(hostname)"
        config_loc="http {"
        config_head="$config_loc\n\tadd_header X-Served-By $host_n;"
        sed -i "s|$config_loc|$config_head|" /etc/nginx/nginx.conf
        sudo service nginx restart
fi
