#!/usr/bin/env bash
# This script is displaying the clock
m=1
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $m -le 59 ]
    do
        echo "$m"
        ((m++))
    done
    m=1
    ((h++))
done
