#!/usr/bin/env bash
# This script is displays the content of the current directory
# in a list format, where only the part of the name after the
# first dash is displaye

for var in *
do
    echo "$var" | cut -f2 -d "-"
done
