#!/usr/bin/env bash
# Script that installs the ufw firewall and setup a few rules

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install ufw

sudo ufw disable && sudo ufw enable

sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

sudo ufw enable
